apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boot-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/UserOlas/argocd-boot-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: boot

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true